#!/usr/bin/env bash

echo "---- README LINKS ----"

grep -oP '\(/[^)]*index\.html\)' README.md \
| tr -d '()' \
| sort > /tmp/readme_links.txt

sed 's|^\./||' <<< "$(find . -name index.html)" \
| sed 's|^|/|' \
| sort > /tmp/filesystem_links.txt

echo
echo "Missing files referenced by README:"
comm -23 /tmp/readme_links.txt /tmp/filesystem_links.txt

echo
echo "Files not referenced in README:"
comm -13 /tmp/readme_links.txt /tmp/filesystem_links.txt
